### ISSUE TITLE
Describe an example of M+L retrieval as an algorithm?

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-loc#16]
The diagram in Fig. 1 is a good visual aid, but the same retrieval workflow could also be described as an algorithm with pseudo-code. It may actually help clarify the diagram, in addition to making it accessible to visually impaired people.

Obviously, we'd need to figure out how to deal with #6 and #7 first.

**Comment by iherman** [comment]
> On 9 Mar 2016, at 15:44, Romain Deltour notifications@github.com wrote:
> 
> The diagram in Fig. 1 is a good visual aid, but the same retrieval workflow could also be described as an algorithm with pseudo-code. It may actually help clarify the diagram, in addition to making it accessible to visually impaired people.
> 
> Obviously, we'd need to figure out how to deal with #6 https://github.com/w3c/dpub-pwp-loc/issues/6 and #7 https://github.com/w3c/dpub-pwp-loc/issues/7 first.

Agreed. I did not mean to say that the diagram is anything else than a visual aid
