### ISSUE TITLE
Change M1 and M2 to Ma and Mb in the definition?

### ISSUE THREAD

**Issue by bjdmeest** [w3c/dpub-pwp-loc#19]
In http://w3c.github.io/dpub-pwp-loc/#dfn-combination-of-manifests, the combination of different manifests is described using M1 and M2.

To avoid confusion with the M2 in http://w3c.github.io/dpub-pwp-loc/#algorithm-to-find-the-right-values-for-lp-and-lu, maybe we can change the numbered M1 and M2 in http://w3c.github.io/dpub-pwp-loc/#dfn-combination-of-manifests to Ma and Mb?

**Comment by iherman** [comment]
Yep, good idea, too. Will do it.

Ivan

> On 11 Mar 2016, at 12:03, Ben De Meester notifications@github.com wrote:
> 
> In http://w3c.github.io/dpub-pwp-loc/#dfn-combination-of-manifests http://w3c.github.io/dpub-pwp-loc/#dfn-combination-of-manifests, the combination of different manifests is described using M1 and M2.
> 
> To avoid confusion with the M2 in http://w3c.github.io/dpub-pwp-loc/#algorithm-to-find-the-right-values-for-lp-and-lu http://w3c.github.io/dpub-pwp-loc/#algorithm-to-find-the-right-values-for-lp-and-lu, maybe we can change the numbered M1 and M2 in http://w3c.github.io/dpub-pwp-loc/#dfn-combination-of-manifests http://w3c.github.io/dpub-pwp-loc/#dfn-combination-of-manifests to Ma and Mb?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/dpub-pwp-loc/issues/19.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
