### ISSUE TITLE
Explicitly describe manifest order?

### ISSUE THREAD

**Issue by bjdmeest** [w3c/dpub-pwp-loc#20]
At the moment, the algorithm implies following order:
1. HTTP Link Header
2. Manifest from package OR manifest as payload OR Manifest embedded in the HTML
3. Manifest via a &lt;link&gt; in &lt;head&gt;

I am not disagreeing, but maybe we should explicitly state this somewhere, to avoid people having to fully parse the algorithm or figure to realize this.

**Comment by iherman** [comment]
Good idea. I will do that.

I.

> On 11 Mar 2016, at 12:08, Ben De Meester notifications@github.com wrote:
> 
> At the moment, the algorithm implies following order:
> 
> HTTP Link Header
> Manifest from package OR manifest as payload OR Manifest embedded in the HTML
> Manifest via a <link> in <head>
> I am not disagreeing, but maybe we should explicitly state this somewhere, to avoid people having to fully parse the algorithm or figure to realize this.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/dpub-pwp-loc/issues/20.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
