### ISSUE TITLE
isn't the real objective of the algorithm to retrieve the manifest?

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-loc#21]
Current it reads "Algorithm to find the right values for Lp and Lu". I think the point of the algorithm is to retrieve the whole **manifest**, why not say so directly ?

There are (or will be) UCs where I need info on the content of the PWP, but don't care about its absolute locator.

Consequently, I'd remove the paragraph starting with:

> In fact, the algorithm does more than...

**Comment by iherman** [comment]
> On 15 Mar 2016, at 17:53, Romain Deltour notifications@github.com wrote:
> 
> Current it reads "Algorithm to find the right values for Lp and Lu". I think the point of the algorithm is to retrieve the whole manifest, why not say so directly ?

I was wondering about that, but I went down this road because the document, really, concentrates on the L-s rather than on the manifest. But it may indeed be cleaner that way. I will do something about that (possibly before the call)

**Comment by iherman** [comment]
I have changed the initial description of the algorithm. Hopefully better... See PR #24.
