### ISSUE TITLE
Are details of manifest retrieval in scope for this Note?

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-loc#23]
To some extent, I still believe that the algorithm and priorities eventually depend on the detailed technical solutions, which are out of scope in the note. For instance:
- we do not (and cannot) describe retrieval and priorities mechanisms in the packaged state
- If I understand correctly, the eventual Spec for PWP can still make the decision that the canonical locator always return a single media type (manifest, or HTML document, or packaged state) –IOW it can discard a conneg approach–, in which case several branches of the algorithm can simply be pruned.

I appreciate that the algorithm definitely clarifies what we're talking about, but IMHO giving it too much "definitive" credit is wishful thinking at this stage?

Part of my concerns are handled in the notes after the algorithm, but I feel that the whole section looks too much "spec like". Shouldn't we just make general statements in this note, and leave the exact mechanisms to the final spec ?

I'm thinking of statements along the line of:
- there can be several manifest resources, to be defined in the final spec.
- manifest have priorities (to be defined), and must eventually be  combined
- HTML allows embedded and linked manifest, in which case embedded should always have higher prio
- manifest can be linked via HTTP headers, in which case it has the higher prio over the payload's manifest

**Comment by iherman** [comment]
> On 16 Mar 2016, at 10:49, Romain Deltour notifications@github.com wrote:
> 
> To some extent, I still believe that the algorithm and priorities eventually depend on the detailed technical solutions, which are out of scope in the note. For instance:
> 
> we do not (and cannot) describe retrieval and priorities mechanisms in the packaged state

You mean _within_ a package, if the package allows for several places for a manifest? Yes, that is correct, and that has to be defined at some later point when packaging for PWP is defined. But that is not inconsistent with this algorithm which considers the package as a black box. 

(Probably worth another note after the algorithm.)

> If I understand correctly, the eventual Spec for PWP can still make the decision that the canonical locator always return a single media type (manifest, or HTML document, or packaged state) –IOW it can discard a conneg approach–, in which case several branches of the algorithm can simply be pruned.
> I appreciate that the algorithm definitely clarifies what we're talking about, but IMHO giving it too much "definitive" credit is wishful thinking at this stage?
> 
> Part of my concerns are handled in the notes after the algorithm, but I feel that the whole section looks too much "spec like". Shouldn't we just make general statements in this note, and leave the exact mechanisms to the final spec ?
> 
> I'm thinking of statements along the line of:
> 
> there can be several manifest resources, to be defined in the final spec.
> manifest have priorities (to be defined), and must eventually be combined
> HTML allows embedded and linked manifest, in which case embedded should always have higher prio
> manifest can be linked via HTTP headers, in which case it has the higher prio over the payload's manifest

Well, this is not a spec. It is, if you like, a proposal for a spec. It may, eventually, be part of a spec and, at that point, it can be pruned. It is an input for a possible spec text, and it is of course only that. An input. But I see it advantageous to have a proposal that is (a) precise when it can, and (b) clearly lists the 'external' design choices that will have to be made.

Maybe this can be mitigated by making some clear statement on the status of the document. Actually, the first decision to be made, eventually, is how this document relates to the PWP draft which, after all, also has a bunch of "spec like" statements when talking about PWP-s and states and whatever. If we merge these two, and we also work on something on manifests (something that we probably should) then we would have a note that is spec like, but clearly does not have all the details settled, and can be completely changed if we get to standardization…

 I do not really see that as a problem at this stage, to be honest.
