### ISSUE TITLE
Should the resources in a PWP follow a hierarchical "tree like" structure?

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp-loc#4]
At the moment, the discussion relies on the fact that the resources follow a "tree like" structures in its local organization, which means that a single base plus the local, relative, URI makes it  possible to find the locator for a resource. This may not always be true; if so, the manifest may require further definitions to ensure a mapping.

This is also related to issue #3.

**Comment by bjdmeest** [comment]
see https://www.w3.org/2016/03/09-dpub-loc-minutes.html#item02 : when a resource comes from another domain, we have no other choice than use an absolute locator. Concerning the hierarchical structure of a PWP: this is not in scope of this task force.
So, in our scope, we can assume a locator to a resource is just (base+)name. We can close this issue without further action.
