### ISSUE TITLE
Do we have to specify what happens when the PWP processor already has a cached version?

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp-loc#5]
I.e., if the user is online, and the online version may be updated, (and P allows for automatic updating,) does the cache than have to be updated? Is this an implementation level issue, or should it be reflected in the specification?

**Comment by bjdmeest** [comment]
see https://www.w3.org/2016/03/09-dpub-loc-minutes.html#item03. Issues on having updatable vs non-updatable PWP's, on how that should be handled, is not in scope of this task force.
Otherwise, whether cache is used is an implementation detail of the PWP processor.
