### ISSUE TITLE
What is the relative priority of various manifests?

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp-loc#6]
When retrieving the manifests a PWP processor may have a number of manifests from different sources that must be combined. If there are overlap in terms, the question of priority comes up: e.g., a manifest coming through a `<link>` element may have a lower priority than the embedded manifest (or the other way round).

Should a PWP specification specify this, or should it be left to implementations

**Comment by rdeltour** [comment]
I would say that this is to be left to a future Rec. We can probably make it clearer in the Note's prose.

**Comment by iherman** [comment]
> On 9 Mar 2016, at 15:51, Romain Deltour notifications@github.com wrote:
> 
> I would say that this is to be left to a future Rec. We can probably make it clearer in the Note's prose.

I am not sure. I think it is important to have that defined even at this stage.

**Comment by bjdmeest** [comment]
See https://www.w3.org/2016/03/09-dpub-loc-minutes.html#item04, consensus is to postpone, as this comes close to be a use case issue.
I tried to reflect the discussion a bit better in the document via 96a6e0ae5f3888afcde048e214b49031df887024
@rdeltour, could you add a reference here to the relevant use case issue, for future reference?

**Comment by iherman** [comment]
Actually… I have started to describe the algorithm and one has to define what M=M1+M2 means. That would raise the relative priority at once….

Let us leave this option open for now and let us see where we are when the whole algorithm is better described.

**Comment by rdeltour** [comment]
> @rdeltour, could you add a reference here to the relevant use case issue, for future reference?

There's no dedicated issue, but the UC from the Locators TF are explicitly mentioned in the [wiki page](https://github.com/w3c/dpub-pwp-ucr/wiki/Use-Cases-Overview) listing the UC to write.
Currently the UC is in a category named "portability", but the categorization there doesn't necessarily reflect what will be in the Note doc.

**Comment by iherman** [comment]
Note that the description of the algorithm has been added in https://github.com/w3c/dpub-pwp-loc/commit/7b6e1ad8ccf3625f89cf8a90b27e37b3e052fbac, and that includes a priority order.
