### ISSUE TITLE
Do we have to be exhaustive in the various options on getting to manifests?

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp-loc#7]
The document contains a description on how the various manifests can be retrieved (and subsequently combined, although see issue #6). Is this description in the spec exhaustive, or are implementations allowed to do more? Does this description defines the _minimal_ alternatives?

**Comment by rdeltour** [comment]
IMO we don't need to be exhaustive in the Note. However, I would expect a Rec to be exhaustive, and even to mandate some options and discard others. In other words, we said the Note should not make assumption on the implementation details; a Rec will hopefully define the technical solution.
